site_name: Flextool - CWatM
site_url: https://cris.vtt.fi/en/organisations/ba4206-design-and-operation-of-energy-systems
site_description: Project documentation for coupling CWatM and IRENA FlexTool
site_author: VTT

repo_url: https://github.com/jeanlouisnico/CWatM-spinetoolbox
edit_uri: blob/master/docs/

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  locale: en
  analytics: {gtag: 'G-274394082'}
  highlightjs: true
  hljs_languages:
    - yaml
    - django
  logo: docs/images/Flextool_original.svg
  favicon: docs/images/Flextool_original.svg
  
nav:
  - About the model: 'about.md'
#  - Overview: introduction.md
#  - Getting started: getting_started.md
#  - Building your model: input_data.md
#  - Example models: example_models.md
#  - References: references.md
plugins:
  - mkdocs-video
  - plotly
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: plotly
          class: mkdocs-plotly
          format: !!python/name:mkdocs_plotly_plugin.fences.fence_plotly
extra:
  homepage: https://cris.vtt.fi/en/organisations/ba4206-design-and-operation-of-energy-systems
  
watch:
  - mkdocs
